name: Docker Image CI

on:
  push:
    branches: [ "certificacion" ]

env:
  tag: $(date +%)
jobs:

  build:

    runs-on: ubuntu-latest

    steps: 
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
         username: ${{ secrets.USER_DOCKER }}
       # Password or personal access token used to log against the Docker registry
         password: ${{ secrets.PASS_DOCKER }}
         
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag bquintero56/pagina:${{env.tag}}
        docker push bquintero56/pagina:${{env.tag}}
        
    - name: docker images 
      run: docker images      
 
